name: Test and lint

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

jobs:

  lint-test:
    name: Quality assurance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Vet
        run : go vet ./...

      - name: Tests
        run: go test ./...
